<DOCTYPE html>
<html>
  <head>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <style>

          header {
              background-color: darkcyan;
          }

          ul {
              list-style: none;
              width: 100%;
          }

          ul li {
              display: inline-block;
              text-align: center;
          }

          header ul li {
              width: 32%;
              margin: 10px 0;
          }

          ul li a {
              text-decoration: none;
          }

          header ul li a {
              color: white;
              font-size: 18px;
              font-weight: bold;
          }

          .messages {
              color: white;
              font-weight: 600;
          }

          .messages .error {
              padding: 10px;
              background-color: lightcoral;
          }

          .messages .success {
              padding: 10px;
              background-color: seagreen;
          }

          #register-lead div {
              display: block;
          }

          #register-lead div label {
              display: block;
          }

          .main {
            margin: 0 2%;
          }
      </style>
  </head>

  <?php
  /** PHP-DI Dependency Injection Manager */
  /** @var \DI\Container $container */

  try {
      /** @var \Example\Utility\UserSession $userSession */
      $userSession = $container->get('\Example\Utility\UserSession');
  } catch (\Exception $exception) {
      $userSession = null;
  }

  try {
      /** @var \Example\Utility\MessageManager $messageManager */
      $messageManager = $container->get('\Example\Utility\MessageManager');
  } catch (\Exception $exception) {
      $messageManager = null;
  }

  ?>

  <body>
    <header>
        <ul>
            <li><a href='/?controller=pages&action=home''>Home</a></li>
            <li><a href='/?controller=dashboard&action=home'>Dashboard</a></li>
            <?php if (!is_null($userSession) && $userSession->getIsLoggedIn()): ?>
                <li><a href='/?controller=dashboard&action=logoutuser'>Logout</a></li>
            <?php else: ?>
                <li><a href='/?controller=dashboard&action=register'>Login</a></li>
            <?php endif; ?>
        </ul>
    </header>

    <div class="main">
        <div class="messages">
            <?php

            if (!is_null($messageManager) && $messageManager->getNumberOfMessagesPending()):
                foreach ($messageManager->getAllMessages() as $message):
                ?>
                <div class="<?php echo $message['type']; ?>"><?php echo $message['message']; ?></div>
                <?php
                endforeach;
                $messageManager->clearAllMessages();
            endif;

            ?>
        </div>
        <div class="main-content">
            <?php require_once('./router/routes.php'); ?>
        </div>
    </div>

    <footer style="margin-top: 20px;">
      Copyright 2018 - Example Demo
    </footer>
  <body>
<html>