<?php
/**
 * @var \Example\Block\Pages\DashboardBlock $block
 */
?>
<h1><?php echo $block->getTitle(); ?></h1>

<table id="register-lead">
    <tr>
        <th>ID</th>
        <th>SESSION ID</th>
        <th>EMAIL</th>
        <th>FIRST NAME</th>
        <th>LAST NAME</th>
        <th>PHONE</th>
        <th>ADDRESS</th>
        <th>SQUARE FOOTAGE</th>
        <th>STATUS</th>
        <th>MODIFIED AT</th>
        <th>CREATED AT</th>
    </tr>

    <?php //var_dump($block->getAllLeads()); echo 'count: '. $block->getAllLeads()->count(); ?>

    <?php if ($block->getAllLeads()->count()):

        foreach ($block->getAllLeads() as $lead):
            /**
             * @var \Example\Model\Leads\LeadsModel $lead
             */
            ?>
            <tr>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getId(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getSessionId(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getEmail(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getFirstname(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getLastname(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getPhone(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getAddress(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getSquareFootage(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getStatus(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getUpdatedAt(); ?></a></td>
                <td><a href="index.php?controller=lead&action=home&id=<?=$lead->getId();?>"><?php echo $lead->getCreatedAt(); ?></a></td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="11">No Leads</td>
        </tr>
    <?php endif; ?>

</table>

<div id="div1"><?php echo json_encode($block->getAllLeads()->toArray()); ?></div>

<script>

</script>