<?php
/**
 * @var \Example\Block\Pages\DashboardBlock $block
 */
?>
<h1><?php echo $block->getTitle(); ?></h1>

<p>Please contact us. Thanks!</p>

<table id="register-lead">
    <tr>
        <th>ID</th>
        <th>SESSION ID</th>
        <th>EMAIL</th>
        <th>FIRST NAME</th>
        <th>LAST NAME</th>
        <th>ADDRESS</th>
        <th>SQUARE FOOTAGE</th>
        <th>MODIFIED AT</th>
        <th>CREATED AT</th>
    </tr>

    <?php foreach ($block->getAllLeads() as $lead): ?>
        <tr>
            <td><?php echo $lead['id']; ?></td>
            <td><?php echo $lead['session_id']; ?></td>
            <td><?php echo $lead['email']; ?></td>
            <td><?php echo $lead['firstname']; ?></td>
            <td><?php echo $lead['lastname']; ?></td>
            <td><?php echo $lead['address']; ?></td>
            <td><?php echo $lead['square_footage']; ?></td>
            <td><?php echo $lead['updated_at']; ?></td>
            <td><?php echo $lead['created_at']; ?></td>
        </tr>
    <?php endforeach; ?>

</table>

<div id="div1"><?php echo json_encode($block->getAllLeads()); ?></div>

<script>

</script>