<?php
/**
 * @var \Example\Block\Pages\HomeBlock $block
 */
?>
<h1><?php echo $block->getTitle(); ?></h1>

<p>Please contact us. Thanks!</p>

<form id="register-lead">
    <div><label for="register-lead" >Email: </label><input type="email" name="email" class="lead-input" /></div>
    <div><label for="register-lead" >First Name: </label><input type="text" name="firstname" class="lead-input" /></div>
    <div><label for="register-lead" >Last Name: </label><input type="text" name="lastname" class="lead-input" /></div>
    <div><label for="register-lead" >Phone: </label><input type="tel" name="phone" class="lead-input" /></div>
    <div><label for="register-lead" >Address: </label><input type="text" name="address" class="lead-input" /></div>
    <div><label for="register-lead" >Square Footage: </label><input type="text" name="square_footage" class="lead-input" /></div>
</form>

<div id="div1"></div>

<script>

    $('.lead-input').on('keyup', function () {

        var form = $('#register-lead');
        var data = form.serialize();

        $.ajax({
            url: "api/leads/leads.php?controller=leads&action=create",
            data: data,
            type: 'post',
            success: function(result){
                $("#div1").html(result);
            }
        });

    });

</script>


