<!--doctype = html-->
<h1>Register</h1>
<form id='register-form' action="/index.php?controller=register&action=create" method="post">
    First Name: <input type="text" name="firstname" /><br />
    Last Name: <input type="text" name="lastname" /><br />
    Email: <input type="email" name="email" /><br />
    Password: <input type="password" name="password" /><br />
    <input type="submit" value="Submit">
</form>